### ISSUE TITLE
How to use this package in a Vite Typescript React project ?

### ISSUE THREAD

**Issue by stouch** [await-ovo/svgr-plugin-swc#1]
Is it possible to use this lib in a React Vite typescript project (with SWC @vitejs/plugin-react-swc) ?

How I'm suppoed to setup tsconfig.json, vite.config.ts and how should I import the svg in my components ?

Thanks a lot

**Comment by await-ovo** [comment]
Hey, I think we can use it together with [vite-plugin-svgr](https://www.npmjs.com/package/vite-plugin-svgr)

**Comment by stouch** [comment]
Thanks! it's working with swc :+1:
